apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: myapi
        image: thiagop4z/myapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: myapi
  namespace: default
spec:
  type: NodePort
  selector:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
