apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      my: api
  template:
    metadata:
      labels:
        my: api
    spec:
      containers:
      - name: myapi
        image: thiagop4z/myapi:latest
---
apiVersion: v1
kind: Service
metadata:
  name: myapi
  namespace: default
spec:
  type: NodePort
  selector:
    my: api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapi
spec:
  rules:
  - host: myapi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapi
            port:
              number: 30000
